ethereum/grid

.github/PULL_REQUEST_TEMPLATE.md
README.md
docs/CONTRIBUTING.md

- Adds contribution guidelines following mist-ui's example
- Adds PR template

docs: adds contribution guidelines

---

README.md

Added the instructions that worked for me

docs: Readme instructions

---

README.md
docs/CONTRIBUTING.md
package.json

Renames project and CI reference

Renaming project

---

ethereum_clients/geth.js
test/geth.test.js

fix: capitalization

---

index.js
package.json
yarn.lock

Fixes update menu bug.
`ElectronMenu` was an API from the AppManager in a previous life.
App manager version bump for local testing.

fix: menu API fix

---

ethereum_clients/geth.js
package.json
test/geth.test.js

adds subscriptions to `geth.js`, listenable on `geth.on(subscriptionId, result => {})`

feat: jsonrpc subscriptions

---

package.json

Fixes builds by including all classes it should.
- 
- 
-

fix: includes all JS files from client plugins to build

---

ethereum_clients/ControlledProcess.js

fix: enforces one log entry per line

---

ethereum_clients/ControlledProcess.js
ethereum_clients/Plugin.js
ethereum_clients/client_plugins/aleth.js
ethereum_clients/client_plugins/geth.js
ethereum_clients/client_plugins/parity.js
package.json

Plugins now have an user-friendly way to change settings on nodes or services.
https://github.com/ethereum/grid/issues/174

feat: Dynamic config

---

.circleci/config.yml
ethereum_clients/Plugin.js
ethereum_clients/client_plugins/geth.js
ethereum_clients/client_plugins/parity.js
ethereum_clients/util.js
package.json
test/settings.test.js

feat: settings changes

---

ethereum_clients/ControlledProcess.js

Emits errors received in stdout and stderr
---
Branch pairs with https://github.com/ethereum/grid-ui/pull/70

fix: emit errors received in stdout and stderr

---

ethereum_clients/ControlledProcess.js
ethereum_clients/Plugin.js

- emits subscription responses under a 'notification' event name.
- implements naive dechunker to concatenate large payloads, e.g. sync subscription with tx hashes
- Note: dechunker just concatenates next incomplete message. Currently low probability, but possible for multiple running clients to concatenate payloads that don't belong together.

fix: notification events and naive dechunking

---

WindowManager.js
electron-shell.js
ethereum_clients/Plugin.js
grid_apps/AppManager.js
grid_apps/apps.json
index.js
package.json
preload-webview.js
preload.js
yarn.lock

Adds a new window "mode" based on window args to display Grid apps.
Provides a list of available apps that can be launched.
Adds an AppManager module and Grid API that opens apps in windows.

feat: add Apps & AppManager

---

ethereum_clients/client_plugins/geth.js
ethereum_clients/client_plugins/parity.js

Adds Görli config settings for parity and geth.

feat: add goerli flags to parity

---

ethereum_clients/client_plugins/examples/plugins.json
ethereum_clients/client_plugins/examples/swarm.js
ethereum_clients/client_plugins/plugins.json

- Stuffs the `swarm.js` file and `plugins.json` config with Raiden into an `examples` directory.
- Added a new `plugins.json` file with an empty array.
Although commented out, Swarm config produced console errors.
closes #242

fix: silo examples

---

ethereum_clients/client_plugins/geth.js
ethereum_clients/client_plugins/parity.js

Part two of #234. Waiting for geth 1.9.x

feat: Adds Goerli network to geth config

---

WindowManager.js

Closes https://github.com/ethereum/grid/issues/300

chore: open new window in offset to existing window

---

ethereum_clients/ControlledProcess.js
ethereum_clients/Plugin.js
ethereum_clients/client_plugins/geth.js

* Adds `write` method to plugin to write to stdin for Terminal Input in https://github.com/ethereum/grid-ui/pull/94
* Adds `Enable console` option in geth

feat: Terminal Input

---

ethereum_clients/Plugin.js
ethereum_clients/PluginHost.js

corresponds to https://github.com/ethereum/grid-ui/pull/98 .
provides getter for plugin source and package metadata.
Important for the UI to determine if plugins are signed:
https://github.com/ethereum/grid/issues/298
https://github.com/ethereum/grid/issues/287

feat: expose plugin source code and metadata to ui

---

ethereum_clients/ControlledProcess.js
ethereum_clients/Plugin.js
ethereum_clients/client_plugins/plugins.json
grid_apps/apps.json

* Adds `IPFS` plugin and app
* Adds a `beforeStart` hook for plugins that can `execute` commands. Used in this case for setting HTTP CORS config for the daemon.
Steps to test:
1. Turn on IPFS
2. Go to `APPS` tab and open `IPFS Web UI`.
3. Check to make sure it's connected. You can try uploading a file as well on the `Files` tab.
--
Should be merged with https://github.com/ethereum/grid-ui/pull/102

feat: IPFS plugin and app

---

grid_apps/AppManager.js

hotfix to display terminal windows

fix: terminal error

---

Config.js
ethereum_clients/PluginHost.js
utils/flags.js

Builds initial flags from default settings. `flags.js` util copied over from grid-ui. Closes https://github.com/ethereum/grid/issues/335.

fix: build initial flags

---

grid_apps/AppManager.js
ui/nano.html

feat: dark mode

---

ethereum_clients/Plugin.js
package.json
ui/nano.html
yarn.lock

Clicking on the terminal icon opens the terminal tab in grid-ui. Closes https://github.com/ethereum/grid/issues/339.
Relies on grid-ui PR: https://github.com/ethereum/grid-ui/pull/106

feat: open to grid-ui terminal

---

nano.js

it prevents grid from being launched more than once by any form (shortcut, taskbar icon, direct from executable).
https://github.com/electron/electron/blob/f6a29707b64bc2f7364f89096d187246bfc53765/docs/api/app.md#apprequestsingleinstancelock
videos.
before: 
https://cdn.discordapp.com/attachments/483981458705350658/603277081840713741/windows-issue.mp4
after:
https://cdn.discordapp.com/attachments/483981458705350658/603277438772051968/windows-instance-lock.mp4
after II:
https://cdn.discordapp.com/attachments/483981458705350658/603281176605491241/Untitled.mov

feat: implements instance lock

---

ethereum_clients/Plugin.js
ui/nano.html

Stores and gets selected release in `config.json`
---
To be paired with https://github.com/ethereum/grid-ui/pull/117

feat: store selected release

---

ui/nano.html

Fixes https://github.com/ethereum/grid/issues/377

fix: add client key

---

ui/nano.html

fix: nano settings icon

---

Menu.js
ethereum_clients/PluginHost.js
nano.js

Restores menu without `Updater` for now.

fix: restore menu

---

nano.js

fix: alwaysOnTop behavior and context menu parity

---

ethereum_clients/client_plugins/geth.js

I made some changes to the geth plugin after doing a thorough run on CentOS-based distro. turns out USB errors popped up because i was on a VM, so no usb drivers.

Geth plugin changes

---

ethereum_clients/client_plugins/geth.js

changes backslash to forward slash
Closes #182

fix(geth): default Windows ipc path

---

README.md

Updates README with the latest links and a screenshot.
First impressions are 🔑. Kept it short and sweet.

chore: update README with latest links and screenshot

---

ethereum_clients/Plugin.js
grid_apps/AppManager.js
preload-webview.js
ui/nano.html

1. Renames many `client` references to `plugin`
1. Adds a quick launch app list to Nano

feat: Nano App List

---

WindowManager.js
ethereum_clients/Plugin.js
ethereum_clients/client_plugins/aleth.js
ethereum_clients/client_plugins/geth.js
ethereum_clients/client_plugins/parity.js
grid_apps/apps.json
ui/nano.html

* Specifies a property `about` on plugins, for use in https://github.com/ethereum/grid-ui/pull/132

feat: about tab

---

ethereum_clients/client_plugins/geth.js

feat: add geth changelog to docs

---

ui/nano.html

Closes https://github.com/ethereum/grid/issues/454
Closes https://github.com/ethereum/grid/issues/449
before:
after:

fix: nano settings bug

---

ethereum_clients/ControlledProcess.js
ethereum_clients/Plugin.js
ui/nano.html

For quicker/more responsive one-click switch change detection in grid-ui

feat: add `downloading` and `extracting` states

---

.github/PULL_REQUEST_TEMPLATE.md

docs: add to PR template

---

RELEASE.md
ethereum_clients/client_plugins/geth.js
grid_apps/apps.json

Introduces basic block explorer app.
- Created with newcomers/workshop attendees in mind. Feature set is minimal, could be easily extended.
- Added some quick docs for releasing apps. Just appended them to the other release docs for now; didn't feel like it merited is own document yet.
- Closes #482

feat: block explorer app

---

ui/nano.html

This PR implements the idea explored in https://github.com/ethereum/grid-ui/pull/160 for nano

fix: disable switch on initial toggle
