ethereum_clients/geth.js
This PR adds a few methods to `geth.js` to enable an IPC connection from the spawned bin.
Experimental, but a better and more secure connection to send RPC requests rather than over HTTP. Use `geth.rpc(method, params)`.
See functions: `getIpcPath`, `connectIpc`, `onIpcData`, `send`, and `rpc` [starting at line 209](https://github.com/ethereum/mist-shell/pull/47/files#diff-d5ac819759156279f21e2446f26105a4R209)
ToDo for future: Subscription (notification) support
=> feat: add geth IPC connection

package.json, renovate.json, yarn.lock
- Adds a prettier precommit hook, for more consistency with the other mist repos.
- Specifies `production` NODE_ENV when running `yarn start:prod`.
- Only applied prettier to `renovate.json` to avoid merge conflicts.
- We should probably also add the same eslint configuration as the other repos too.
husky, lint-staged, prettier
=> chore: adds prettier precommit hook

scripts/copyApp.js
- updates copy script; mist-ui path + AppManager API
- (prettier did the rest)
=> fix: copyApp script

CONTRIBUTING.md, README.md, RELEASE.md
First pass at documenting the build process. Closes https://github.com/ethereum/grid/issues/79.
=> chore: release docs

WindowManager.js, ethereum_clients/geth.js
Emit on new logs.
This will remove the need to poll for new log entries in grid-ui/Terminal.jsx component, and instead can subscribe to `geth.on('log', log => { console.log('New log: ', log) })`
Also increases electron window width a little bit to make for roomier terminal.
=> feat: emit logs

preload.js
Allows for `grid-ui` to open a native open folder dialog with https://github.com/ethereum/grid-ui/pull/35
=> feat: native open folder dialog

ethereum_clients/ControlledProcess.js
Back-end fix of #157.
We can't assume all log events will come with a single line each. This fix makes sure we'll split them into lines and appends them individually to the `logs` array
=> Fix: properly split logs in lines when receives a larger chunk

ethereum_clients/ControlledProcess.js, ethereum_clients/Plugin.js, ethereum_clients/PluginHost.js, ethereum_clients/client_plugins/plugins.json, ethereum_clients/util.js, index.js, package.json, yarn.lock
It extends the PluginHost with functionality to process a list `plugins.json` of externally hosted plugins and allows to download & cache them, verify their signatures and eventually load them in the main process during runtime. These plugins are stored in a path outside of the main app so that changes to them don't require elevated user permissions or re-installation.
The purpose of this PR is to give external projects more control and autonomy over their integrations and the release lifecycle. Moreover, changes to external plugins won't affect Grid's release cycle since such plugins can be updated, removed and reloaded during runtime.
*Problem*: the renderer start is deferred until *all* plugins (local & remote) are processed. This is mostly done because otherwise it would require …
=> feat: support externally hosted plugins

ethereum_clients/ControlledProcess.js
Adds start cmd to first line of logs
Closes https://github.com/ethereum/grid/issues/213
=> feat: add start cmd to logs

ethereum_clients/client_plugins/parity.js
`config` removed in favor of defaults within `settings`
=> fix: remove stale parity config

ethereum_clients/client_plugins/geth.js
This pr encloses datadir in quotes, so if the field is left blank, it does not take the following flag as a parameter.
Fixes use case described below:
> Within geth config, empty `dataDir` field and try to start it.
Please try it in current grid then on this PR.
Closes https://github.com/ethereum/grid/issues/237
=> fix: geth flag pattern

ethereum_clients/client_plugins/geth.js
Reverts ethereum/grid#238; Successfully addresses the datadir path bug for me. Please test @evertonfraga.
=> fix: Revert "fix: geth flag pattern"

ethereum_clients/client_plugins/parity.js
Grabs Parity releases from a mirror repository, as app manager does not support unpackaged binaries. this new mirror is maintained by myself for now.
=> chore: fetching parity binaries from another repo

.circleci/config.yml
Here we want to compare the two outcomes of builds made against master and other branches: 
```
- &run_script
run: | 
if [[ $CIRCLE_BRANCH == 'master' ]]; then
yarn release --$GRID_ENV;
else
yarn build --$GRID_ENV;
fi;
```
https://github.com/ethereum/grid/blob/master/.circleci/config.yml#L58-L63
Closes #229
=> ci: publishing assets only from `master`

ethereum_clients/ControlledProcess.js, ethereum_clients/Plugin.js, grid_apps/apps.json, preload-webview.js
Adds a [Grid RPC Tester app](https://github.com/ryanio/grid-rpc-app) that detects plugins and sends RPC commands to them, or can set to a custom endpoint.
1. Adds `grid.getAllPlugins()` to populate plugin dropdown list
2. Emits a new event `newState` for any new state updates. I developed this pattern for my clef app, which makes it useful to listen to one event for new plugin status updates, rather than creating a new listener for every 'starting'|'started'|'connected'|'stopped' etc.
1. Also adds a new state `disconnected` for a plugin that's still running but whose rpc/ipc got disconnected
---
Closes https://github.com/ethereum/grid/issues/263
Closes https://github.com/ethereum/grid/issues/256
=> feat: RPC Tester App

ethereum_clients/client_plugins/aleth.js
Uses `prefix` to filter Aleth releases for mac / linux.
Fixes #240.
Open Aleth plugin and check if all releases are for the current platform. Keep in mind they do not have windows binaries for all releases
=> Fix aleth filter

ethereum_clients/client_plugins/geth.js, ethereum_clients/client_plugins/parity.js, preload-webview.js, preload.js, utils/renderer/electron.js
Renames `openFolderDialog` to `showOpenDialog` and accepts `file` or `directory` (or `file_multiple` or `directory_multiple`)
Closes https://github.com/ethereum/grid/issues/274
Pairs with https://github.com/ethereum/grid-ui/pull/90
=> feat: expands showOpenDialog to accept `file` or `directory`

Config.js
Adds a default `settings` key for grid-ui to populate with plugin settings.
=> feat: introduces settings to config.json

ethereum_clients/client_plugins/geth.js, grid_apps/apps.json
* Adds `graphql` flag to geth plugin
* Adds localhost `graphiql` app to apps
* Closes https://github.com/ethereum/grid/issues/323
=> feat: geth graphql

ethereum_clients/ControlledProcess.js, ethereum_clients/Plugin.js
After https://github.com/ethereum/grid-ui/pull/89 is merged, this PR will be safe to merge to remove the old individual state event emits.
@PhilippLgh do any of your apps use these old state events that I should PR to update to using `.on('newState' ...)` before this is merged in? Thx
---
Closes https://github.com/ethereum/grid/issues/279
=> chore: remove old state events, in favor of `newState` event

ui/nano.html
- Adds classes for each os (mac|linux|windows)
- Changes CSS rules according to desired UI
- Renames classes for window position
Mac: 
Windows + Linux
=> fix: removing window tip on linux + windows

nano.js, preload.js, ui/nano.html, utils/renderer/electron.js
- hides window when focus is lost
1. click on any other app
1. open "Apps"
1. open any client config window
- context menu to keep nano opened (super useful for debug or advanced use)
=> Nano window visibility control

nano.js, ui/nano.html
Fixes `MaxListenersExceededWarning` in nano due to calling 
```js
const clientPlugin = window.Grid.PluginHost.getPluginByName(this.client.name)
```
every time list is rendered (i.e. switching back and forth from settings cog).
Fixes by passing in a reference to the plugin through the `client` prop.
---
For future consideration, we should revisit the PluginProxy architecture so a `new PluginProxy` isn't created every time on `getAllPlugins()` and `getPluginByName()`:
```js
getAllPlugins() {
return this.plugins.map(p => new PluginProxy(p))
}
getPluginByName(name) {
return this.getAllPlugins().find(p => p.name === name)
}
```
which in turn calls memory leaking function in `PluginProxy` constructor `registerEventListeners()`:
```js
registerEventListeners(sourceEmitter, destEmitter) {
// FIXME …
```
=> fix: nano MaxListenersExceededWarning

ui/nano.html
Matches nano switch color to the same green used by grid-ui.
Hunting for release blog post screenshots.
=> fix: nano switch color

ethereum_clients/PluginHost.js
Caches PluginProxy so it does not create a new PluginProxy on every new `getAllPlugins()` or `getPluginByName()`, which would set up listeners every time and create a memory leak.
=> chore: cache PluginProxy

WindowManager.js, grid_apps/AppManager.js, nano.js
My center offset code was being thrown off by new nano menubar, so there was a x/y coordinate hardcoded in.
This fixes with better logic to calculate opening to center of screen with offset based on number of open windows (except nano).
To test:
1. Start Grid
1. Click on 'Geth' in Nano, grid-ui should open in center
1. Without closing previous window, click on 'IPFS' in Nano, grid-ui should open in center offset
=> fix: launches AppManager windows in center with offset

ui/nano.html
With the addition of the Apps icon, the "grid" logo got pushed further to the left, off-center.
before:
after:
=> fix: properly spaces nano title

nano.js
This PR attempts to fix those two behaviors, on mac and win:
1) removes blur event, attempting to fix windows issue. https://github.com/ethereum/grid/commit/77f59e47bb4fd303fa73be55a9f3879f5b221e70
2) now, whenever a user closes nano using Esc key on Mac, the icon should not remove its highlighted state (a side-effect of changes made in **1**). https://github.com/ethereum/grid/commit/244babe32c7be3820b0ab1632af6d87cdfe2ed2c
3) changes context menu checkbox to toggle AlwaysOnTop property. https://github.com/ethereum/grid/commit/7e27eb0d2715f3a83694d99de7268e29c9b8d057
=> fix: window visibility control

ui/nano.html
Uses the correct API for plugin, using `off` instead of `removeEventListener`
There should be no more errors in console when switching over to the settings cog.
---
Fixes https://github.com/ethereum/grid/issues/382
=> fix: change `removeEventListener` to `off` to fix error

ethereum_clients/ControlledProcess.js
Matches error as a separate whole word to pass as pluginError
Fixes https://github.com/ethereum/grid/issues/385
=> fix: match error to whole word for pluginError

nano.js, ui/nano.html
Replaces "View Apps" link with a feedback form link, since the Apps page link was added to the top of nano.
=> fix: remove duplicate Apps links

nano.js
It preserves nano window size and does not stretch it out when going fullscreen from any of grid UI windows.
=> fix: nano does not go fullscreen on macos

ethereum_clients/client_plugins/geth.js
Capitalizes geth sync labels.
This was driving me nuts. These values were the only ones not capitalized in the form.
before:
=> fix: adds uppercase geth sync labels

ethereum_clients/client_plugins/parity.js
Introduces `required` flags. Closes https://github.com/ethereum/grid/issues/442
I like this solution because: 
A) the plugin config code is a little verbose, but requires no changes to the complicated flag generation logic, and 
B) users can still go wild and override the flags in the custom flag section
Note: assuming you have some stored values for Parity configs, you will likely have to toggle custom flags on and off to see the new ones appear.
=> feat: introduces required flags for parity

nano.js
Shuts down lingering processes on quit. Closes #267.
Moved the instantiation of the PluginHost out of the `mb.on('ready', () => {})` callback function. I didn't notice any unintended consequences, but its possible there are implications I'm not aware of. 👀 appreciated.
=> fix: shut down lingering plugins

ui/nano.html
Fixes https://github.com/ethereum/grid/issues/418
* Clears error in nano when receiving the plugin event `clearPluginErrors`
* added in https://github.com/ethereum/grid-ui/pull/139
* If a plugin has an error, clicking on its title will bring you direct to Terminal tab
=> feat: clear errors in nano on plugin event `clearPluginErrors`

ethereum_clients/ControlledProcess.js, ethereum_clients/Plugin.js, yarn.lock
- Fix for nano getting out of sync with grid-ui. Please review @ryanio as git blame indicates you added the function just a couple days ago.
before:
=> fix: out of sync nano

ethereum_clients/ControlledProcess.js, ethereum_clients/Plugin.js, preload-webview.js, ui/nano.html
Add `getErrors` and `dismissError` for plugins.
=> feat: add plugin getErrors and dismissError(key)

scripts/copyApp.js
Updates `copyApp.js` to latest code from @PhilippLgh
=> fix: update copyApp.js from philipp

nano.js
Hides nano onBlur for mac.
I believe this is the ideal UX, but Windows can't handle it due to a bug (which I can't recall the specifics of anymore - if someone does, it may be helpful to include more context in the comment.)
=> fix: hide nano on blur for mac

ethereum_clients/Plugin.js
It allows extraction of clients from its packages for multiple times, and not only once.
This PR removes the caching of the variable `this.binPath` on Plugin.js.
=> fix: binary path variable cache was preventing other versions to be extracted

grid_apps/AppManager.js, nano.js, package.json, utils/main/util.js, yarn.lock
- activates the main app's updater
- limits grid-ui versions to version range of grid
- fixes the timeout received on linux tests, when opening grid-ui
=> Updater fixes

nano.js
- Fixes blank `contextMenu` for menubar icon on Linux.
- Adds "Toggle window" menu option as this is the only way to do display Nano on Linux.
- Uses higher resolution icon, borrowed from macos.
My tests were made on Ubuntu 18.04 (Virtualbox) and Amazon Linux (AWS Workspaces), which is RedHat/CentOS based.
1. Grab Grid binaries from the [CI job](https://circleci.com/gh/ethereum/grid/2627)
2. Load it to your VM
3. Profit
Closes #398
=> Fix: menubar contextMenu on linux

package.json, yarn.lock
electron-app-manager version bump
=> chore: bump app manager version

ethereum_clients/ControlledProcess.js
I was experiencing on the Windows VM anytime I turned off a plugin I would get this error message:
This PR adds a null check to that error message.
=> fix: add null check

ethereum_clients/client_plugins/geth.js
For some reason, the keystore dir for geth was being set incorrectly. This fixes that.
=> fix: default geth keystore dir

RELEASE.md
Adds an omitted `-r` flag in the zip instructions and improves context.
=> docs: improve app release docs

ethereum_clients/client_plugins/geth.js, package.json
chore: bump version (1.6.2), and better formatting of keystorePath for windows
=> chore: bump version (1.6.2)

ethereum_clients/client_plugins/geth.js
Better concise (bug-free) definition of keystoreDir in `geth.js`
=> fix: keystore dir definition

ethereum_clients/client_plugins/geth.js, utils/flags.js
Removes trying to define default data directory and keystore directory across platforms, and instead introduces property `ignoreIfEmpty` to flag settings.
Closes one of the issues in #512
Pairs with https://github.com/ethereum/grid-ui/pull/159
---
To test, run this branch with the paired grid-ui branch and see what your values in Settings are for Geth for `Data Directory` and `Keystore Directory`. Clear them empty, and see if the generated flags hide --datadir and/or --keystoredir
=> feat: ignore flag if empty
